: "${XDG_CONFIG_HOME:=${HOME}/.config}"
: "${XDG_DATA_HOME:=${HOME}/.local/share}"
: "${XDG_CACHE_HOME:=${HOME}/.cache}"

typeset -g ZSH_AUTOCOMPLETIONS_CONFIG_DIR="${XDG_CONFIG_HOME}/zsh"
typeset -g ZSH_AUTOCOMPLETIONS_SITE_FUNCTIONS_DIR="${XDG_DATA_HOME}/zsh/site-functions"
typeset -g ZSH_AUTOCOMPLETIONS_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
typeset -g ZSH_AUTOCOMPLETIONS_STAMP_FILE="${ZSH_AUTOCOMPLETIONS_CACHE_DIR}/autocompletions.stamp"
typeset -g ZSH_AUTOCOMPLETIONS_LOCK_ROOT="${XDG_RUNTIME_DIR:-${ZSH_AUTOCOMPLETIONS_CACHE_DIR}}"
typeset -g ZSH_AUTOCOMPLETIONS_LOCK_DIR="${ZSH_AUTOCOMPLETIONS_LOCK_ROOT}/autocompletions.lock"

typeset -gU fpath
fpath=("${ZSH_AUTOCOMPLETIONS_SITE_FUNCTIONS_DIR}" "${fpath[@]}")
