#!/bin/sh

civics_bot_dir="$HOME/workspace/civics"
bin="$HOME/bin"
tg="$bin/tg"

cd "$civics_bot_dir"
payload="$(./pick_qa.sh | ./qa_to_tg_payload.sh)"
exec snooze -H '8-20' -M '/15' bash -c "$tg send 'peifen' '$payload' && $tg send 'sam' '$payload'"
