#!/usr/bin/env bash
# unofficial strict mode
# note bash<=4.3 chokes on empty arrays with set -o nounset
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
# https://sharats.me/posts/shell-script-best-practices/
set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
shopt -s nullglob globstar

[[ "${TRACE:-0}" == '1' ]] && set -o xtrace

XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
TIMEFILE="$XDG_STATE_HOME/move-lockouts/last-run.timefile"
INTERVAL="$((40 * 60))"

main() {
  mkdir -p "$(dirname "$TIMEFILE")"
  touch "$TIMEFILE"

  # wait either for a modify on `$TIMEFILE` or for `$INTERVAL` seconds to elapse
  if inotifywait --quiet --timeout "$INTERVAL" --event 'attrib' "$TIMEFILE"; then
    notify-send "[move-lockouts] reset - waiting ${INTERVAL}s ⏳"
    return
  fi

  # timeout expired → attempt a lock
  ./lock-if-screen-on.bash
}

main "$@"

exit 0
